### ISSUE TITLE
mAP 可视化参数

### ISSUE THREAD

**Issue by YINGNANSU** [zhengye1995/underwater-objection-detection#13]
请问在analyze_logs.py中，如果要可视化mAP，参数如何设置？ 
导入了log.json文件之后， '--keys bbox_mAP', '--keys mAP',  都有尝试过，但是不行。

**Comment by zhengye1995** [comment]
It is because that I do not validate model during training, so there is not 'bbox_mAP' or 'mAP' in log file, if you what to get mAP, you can just use eval tool from COCO, you can also try add --eval bbox during test.
