### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by lrrll** [zhengye1995/underwater-objection-detection#15]
Hello, I am a student of Ocean University of China. After registering the contest at that time, personal reasons were put on hold, and the data set was not downloaded in time. Because my current research direction is also on sonar, can I share the data set privately? Thanks!

**Comment by zhengye1995** [comment]
您好：
    您是想要水下声学的雷达的数据还是水下光学的数据呢。


郑烨
祝好


On 7/1/2020 17:07，lrrll<notifications@github.com> wrote：

Hello, I am a student of Ocean University of China. After registering the contest at that time, personal reasons were put on hold, and the data set was not downloaded in time. Because my current research direction is also on sonar, can I share the data set privately? Thanks!

**Comment by Lele-Zhou** [comment]
老哥，水下声学数据集可否发下网盘链接，574820506@qq.com，谢谢！

**Comment by daqian90** [comment]
> 您好： 您是想要水下声学的雷达的数据还是水下光学的数据呢。 郑烨 祝好 On 7/1/2020 17:07，lrrll<notifications@github.com> wrote： Hello, I am a student of Ocean University of China. After registering the contest at that time, personal reasons were put on hold, and the data set was not downloaded in time. Because my current research direction is also on sonar, can I share the data set privately? Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

求老哥分享水下声学数据集，294251231@qq.com，谢谢

**Comment by zhengye1995** [comment]
> > 您好： 您是想要水下声学的雷达的数据还是水下光学的数据呢。 郑烨 祝好 On 7/1/2020 17:07，lrrll[notifications@github.com](mailto:notifications@github.com) wrote： Hello, I am a student of Ocean University of China. After registering the contest at that time, personal reasons were put on hold, and the data set was not downloaded in time. Because my current research direction is also on sonar, can I share the data set privately? Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 求老哥分享水下声学数据集，[294251231@qq.com](mailto:294251231@qq.com)，谢谢

please see your email.
