### ISSUE TITLE
the version of mmcv

### ISSUE THREAD

**Issue by ZeKunZhang1998** [zhengye1995/underwater-objection-detection#16]
could u tell me the version of mmcv？I always 'no module name mmdel'.

**Comment by milleniums** [comment]
0.2.16

**Comment by milleniums** [comment]
> could u tell me the version of mmcv？I always 'no module name mmdel'.

0.2.16

**Comment by zhengye1995** [comment]
mmcv==0.2.16

**Comment by ZeKunZhang1998** [comment]
> > could u tell me the version of mmcv？I always 'no module name mmdel'.
> 
> 0.2.16
thanks ,but I still have that problem.

**Comment by ZeKunZhang1998** [comment]
> > could u tell me the version of mmcv？I always 'no module name mmdel'.
> 
> 0.2.16

Thanks!

**Comment by ZeKunZhang1998** [comment]
> mmcv==0.2.16

when I use it on Colab

**Comment by zhengye1995** [comment]
Did you build the mmdet with 
```
python setup.py develop
```
successful?
