### ISSUE TITLE
KeyError: 'Underwater is not in the dataset registry'

### ISSUE THREAD

**Issue by jajajajaja121** [zhengye1995/underwater-objection-detection#6]
升级mmdetection版本之后训练显示上述错误，请问升级之后还需要做哪些改变才能正常训练？

**Comment by zhengye1995** [comment]
Did you put my code about 'Underwater' dataset in your new version?

**Comment by jajajajaja121** [comment]
yes, mmdet/dataset/underwater have I miss something?



发自我的小米手机
在 zhengye <notifications@github.com>，2020年3月24日 下午4:14写道：

Did you put my code about 'Underwater' dataset in your new version?

**Comment by zhengye1995** [comment]
All lines about this：
https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/datasets/__init__.py#L11

https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/datasets/__init__.py#L17

https://github.com/zhengye1995/underwater-objection-detection/blob/master/mmdet/datasets/underwater.py

https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/core/evaluation/class_names.py#L4

If all of these code are exist, maybe you should rebuild mmdetection again if your code model is not in develop model.

**Comment by jajajajaja121** [comment]
Thanks a lot

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zhengye <notifications@github.com>
发送时间: Tuesday, March 24, 2020 5:21:27 PM
收件人: zhengye1995/underwater-objection-detection <underwater-objection-detection@noreply.github.com>
抄送: jajajaja <skyrim19961234@outlook.com>; Author <author@noreply.github.com>
主题: Re: [zhengye1995/underwater-objection-detection] KeyError: 'Underwater is not in the dataset registry' (#6)


All lines about this：
https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/datasets/__init__.py#L11

https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/datasets/__init__.py#L17

https://github.com/zhengye1995/underwater-objection-detection/blob/master/mmdet/datasets/underwater.py

https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/core/evaluation/class_names.py#L4

If all of these code are exist, maybe you should rebuild mmdetection again if your code model is not in develop model.

―

**Comment by jajajajaja121** [comment]
After I updata these code, another error happened, AttributeError: 'ConfigDict' object has no attribute 'seed', I don’t know why.


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zhengye <notifications@github.com>
发送时间: Tuesday, March 24, 2020 5:21:27 PM
收件人: zhengye1995/underwater-objection-detection <underwater-objection-detection@noreply.github.com>
抄送: jajajaja <skyrim19961234@outlook.com>; Author <author@noreply.github.com>
主题: Re: [zhengye1995/underwater-objection-detection] KeyError: 'Underwater is not in the dataset registry' (#6)


All lines about this：
https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/datasets/__init__.py#L11

https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/datasets/__init__.py#L17

https://github.com/zhengye1995/underwater-objection-detection/blob/master/mmdet/datasets/underwater.py

https://github.com/zhengye1995/underwater-objection-detection/blob/3fe7433b513a3fdcf3f76a53937355632d486753/mmdet/core/evaluation/class_names.py#L4

If all of these code are exist, maybe you should rebuild mmdetection again if your code model is not in develop model.

―

**Comment by zhengye1995** [comment]
Sorry I do not use mmd of new version, I guess you should add seed in config file, you can compare my config file with new version's.

**Comment by jajajajaja121** [comment]
Ok, thank you

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zhengye <notifications@github.com>
发送时间: Wednesday, March 25, 2020 11:14:04 AM
收件人: zhengye1995/underwater-objection-detection <underwater-objection-detection@noreply.github.com>
抄送: jajajaja <skyrim19961234@outlook.com>; Author <author@noreply.github.com>
主题: Re: [zhengye1995/underwater-objection-detection] KeyError: 'Underwater is not in the dataset registry' (#6)


Sorry I do not use mmd of new version, I guess you should add seed in config file, you can compare my config file with new version's.

―

**Comment by jajajajaja121** [comment]
This error solved by replace dist_train.sh in new version’s.


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zhengye <notifications@github.com>
发送时间: Wednesday, March 25, 2020 11:14:04 AM
收件人: zhengye1995/underwater-objection-detection <underwater-objection-detection@noreply.github.com>
抄送: jajajaja <skyrim19961234@outlook.com>; Author <author@noreply.github.com>
主题: Re: [zhengye1995/underwater-objection-detection] KeyError: 'Underwater is not in the dataset registry' (#6)


Sorry I do not use mmd of new version, I guess you should add seed in config file, you can compare my config file with new version's.

―

**Comment by zhengye1995** [comment]
Congratulations, and I close this comment.
