### ISSUE TITLE
捉个readme小虫？

### ISSUE THREAD

**Issue by ShinoSpace** [zhengye1995/underwater-objection-detection#7]
First thanks to your generous open source.
location in readme: predict cmd of htc:
x101_64x4d (htc pretrained):

chmod +x tools/dist_test.sh

./tools/dist_test.sh configs/underwater/**_cas_se_**/cascade_rcnn_x101_64x4d_fpn_1x.py workdirs/cas_x101_64x4d_fpn_htc_1x/latest.pth 4 --json_out results/cas_x101.json

I think it may should be:
x101_64x4d (htc pretrained):

chmod +x tools/dist_test.sh

./tools/dist_test.sh configs/underwater/**_cas_x101_**/cascade_rcnn_x101_64x4d_fpn_1x.py workdirs/cas_x101_64x4d_fpn_htc_1x/latest.pth 4 --json_out results/cas_x101.json

of course it is not a severe problem and maybe i just much ado about nothing. 2333

**Comment by zhengye1995** [comment]
Thank you very much to point this issue, I will fix it.
